celsius = input('섭씨온도:')
celsius = int(celsius)
fahrenheit = (9/5) * celsius + 32
print('섭씨',end='')
print('',celsius,end='')
print(' 도는',end='')
print(' 화씨',end='')
print('',fahrenheit,end='')
print(' 도입니다',end='')
